#Config File for DuelsPE
---
#Plugin by corytortoise

######################
#            Match Settings          
######################

#How long the countdown to a match is in seconds.
countdown: 5
#How long each round lasts in seconds.
time-limit: 180

#Whether or not tapping a Duel sign adds you to the queue.
sign-join: true

#Should kits be forced? If false, players will duel with the items they have with them.
#If true, their inventories will be cleared and they will receive the configured kits.
force-kits: true

######################
#                  Kits          
######################

#Maybe add support for kit plugins later?

#Kit
kit:
  type: custom
#
  items:
  - id: "276:0:1"
  - id: "364:0:16"
  - id: "306:0:1"
  - id: "307:0:1"
  - id: "308:0:1"
  - id: "309:0:1"
  

